export const API_ENDPOINTS = {
  AUTH_GOOGLE: '/auth/google',
  AUTH_APPLE: '/auth/apple',
  AUTH_LOGOUT: '/auth/logout',
  AUTH_ME: '/auth/me',
  USERS_ME: '/users/me',
  USERS_AVATAR: '/users/me/avatar',
  USERS_CURRENCIES: '/users/currencies',
  USERS_SEARCH: '/users/search',
  GROUPS: '/groups',
  GROUP_DETAIL: (groupId: string) => `/groups/${groupId}`,
  GROUP_REMOVE_MEMBER: (groupId: string, userId: string) => `/groups/${groupId}/members/${userId}`,
  GROUP_UPDATE_MEMBER_ROLE: (groupId: string, userId: string) =>
    `/groups/${groupId}/members/${userId}/role`,
  GROUP_INVITES: (groupId: string) => `/groups/${groupId}/invites`,
  GROUP_INVITE_CANCEL: (groupId: string, inviteId: string) =>
    `/groups/${groupId}/invites/${inviteId}`,
  GROUP_JOIN: (token: string) => `/groups/join/${token}`,
  GROUP_JOIN_BY_CODE: '/groups/join',
  GROUP_POOLS: (groupId: string) => `/groups/${groupId}/pools`,
  GROUP_EXPENSES: (groupId: string) => `/groups/${groupId}/expenses`,
  GROUP_BALANCES: (groupId: string) => `/groups/${groupId}/balances`,
  POOL_DETAIL: (poolId: string) => `/pools/${poolId}`,
  POOL_MEMBERS: (poolId: string) => `/pools/${poolId}/members`,
  POOL_REMOVE_MEMBER: (poolId: string, userId: string) => `/pools/${poolId}/members/${userId}`,
  POOL_EXPENSES: (poolId: string) => `/pools/${poolId}/expenses`,
  POOL_PARSE_RECEIPT: (poolId: string) => `/pools/${poolId}/expenses/parse-receipt`,
  EXPENSE_DETAIL: (poolId: string, expenseId: string) => `/pools/${poolId}/expenses/${expenseId}`,
  EXPENSE_RECURRENCE: (poolId: string, expenseId: string) =>
    `/pools/${poolId}/expenses/${expenseId}/recurrence`,
  UPCOMING_EXPENSES: '/users/me/expenses/upcoming',
  USER_ACTIVITIES: '/users/me/activities',
  BALANCES: '/balances',
  POOL_BALANCES: (poolId: string) => `/pools/${poolId}/balances`,
  POOL_SETTLEMENTS: (poolId: string) => `/pools/${poolId}/settlements`,
  SETTLEMENT_DETAIL: (settlementId: string) => `/settlements/${settlementId}`,
  SETTLEMENT_CONFIRM: (settlementId: string) => `/settlements/${settlementId}/confirm`,
  SETTLEMENT_DISPUTE: (settlementId: string) => `/settlements/${settlementId}/dispute`,
  NOTIFICATIONS: '/notifications',
  NOTIFICATION_READ: (id: string) => `/notifications/${id}/read`,
  NOTIFICATIONS_READ_ALL: '/notifications/read-all',
  NOTIFICATIONS_DEVICE_TOKEN: '/notifications/device-token',
  NOTIFICATIONS_DEVICE_TOKEN_DELETE: (playerId: string) =>
    `/notifications/device-token/${playerId}`,
  NOTIFICATIONS_PREFERENCES: '/notifications/preferences',
  CATEGORIES: '/categories',
  CATEGORY_DETAIL: (categoryId: string) => `/categories/${categoryId}`,
  GROUP_WEBHOOKS: (groupId: string) => `/groups/${groupId}/webhooks`,
  GROUP_WEBHOOK_DELETE: (groupId: string, webhookId: string) =>
    `/groups/${groupId}/webhooks/${webhookId}`,
} as const;
